# Generated by Django 6.0.2 on 2026-02-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(blank=True, default=1978, null=True),
        ),
    ]
